**Basics Of Numpy**

In [2]:
import numpy as np

In [2]:
a = np.array([[]])
a.ndim

2

In [3]:
range = np.arange(0,12,2)
range

array([ 0,  2,  4,  6,  8, 10])

In [4]:
arr = np.linspace(0,2,10)
arr

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [5]:
arrlog = np.logspace(1,3,2)
arrlog

array([  10., 1000.])

In [6]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [7]:
arr = np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr = np.ones([4,3] , dtype = int)
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
arr = np.full(10,2)
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
arr = np.full([4,3] , 7)
arr

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [12]:
arr = np.empty([2,2])
arr

array([[2.99181375e-315, 0.00000000e+000],
       [6.65613579e-310, 6.65613570e-310]])

In [13]:
arr = np.random.rand(12)
arr

array([0.16125452, 0.35870616, 0.09070332, 0.18950423, 0.76287515,
       0.34727683, 0.50899929, 0.5528613 , 0.47715441, 0.48234424,
       0.69890526, 0.41011683])

In [15]:
arr = np.random.rand(2,3)
arr

array([[0.52897175, 0.39829014, 0.97632891],
       [0.10373969, 0.72254381, 0.37786922]])

In [16]:
arr = np.random.randint(10,100)
arr

53

In [17]:
arr = np.random.randint(10,100, size = [2,3])
arr

array([[97, 19, 96],
       [57, 37, 74]])


***Numpy Data Types and Type Casting***

In [18]:
arr = np.array([1,2,3,1.1,2.3,4,5,6,7])
arr

array([1. , 2. , 3. , 1.1, 2.3, 4. , 5. , 6. , 7. ])

In [19]:
arr.dtype

dtype('float64')

In [21]:
lst = ["string" , 1, 2, '3' , 4 , 5]
arr = np.array(lst)
arr


array(['string', '1', '2', '3', '4', '5'], dtype='<U21')

In [22]:
arr.dtype

dtype('<U21')

In [23]:
arr = np.array([1,2,3,4,5,6.7,7.6] , dtype = np.int64)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
arr.dtype

dtype('int64')

In [26]:
arr = np.array([1.23,3.456,6,7.89] , dtype = np.int64)
arr

array([1, 3, 6, 7])

In [27]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [28]:
arr.dtype

dtype('int64')

In [29]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3., 4., 5.])

In [30]:
new_arr.dtype

dtype('float64')

In [31]:
new_arr2 = new_arr.astype(np.int64)
new_arr2

array([1, 2, 3, 4, 5])

In [32]:
new_arr.dtype

dtype('float64')

In [33]:
arr_3 = np.array([[1,2,3] ,[4,5,6]])
arr_3

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr_3.ndim

2

In [36]:
arr_3.size

6

In [37]:
arr_3.itemsize

8

*Array Reshaping , Ravel , Flatten*

In [38]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = arr1.reshape(2,3)


In [39]:
arr1

array([1, 2, 3, 4, 5, 6])

In [40]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr3 = arr2.reshape(3,2)
arr3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
ravel = arr3.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [46]:
ravel[0] = 100
ravel[1] = 200
ravel


array([100, 200,   3,   4,   5,   6])

In [47]:
arr3

array([[100, 200],
       [  3,   4],
       [  5,   6]])

In [51]:
arr4 = np.array([3,4,5,6,7,8])
arr5 = arr4.reshape(2,3)

In [52]:
arr5

array([[3, 4, 5],
       [6, 7, 8]])

In [53]:
flat = arr5.flatten()
flat

array([3, 4, 5, 6, 7, 8])

In [54]:
flat[0] = 300
flat

array([300,   4,   5,   6,   7,   8])

In [55]:
arr5

array([[3, 4, 5],
       [6, 7, 8]])

Arithematic Operations

In [56]:
a = np.array([4,8,16])
b = np.array([2,4,8])

In [57]:
#Addition
c = a + b
c

array([ 6, 12, 24])

In [58]:
#substraction
d = a-b
d

array([2, 4, 8])

In [59]:
#Multiplication
e = a * b
e

array([  8,  32, 128])

In [60]:
#Integer Division
f = a//b
f

array([2, 2, 2])

In [61]:
#Division
g = a/b
g

array([2., 2., 2.])

In [62]:
#modulation
k = a&b
k

array([0, 0, 0])

In [63]:
#exponent power
o = a ** b
o

array([        16,       4096, 4294967296])

Indexing and Slicing

In [3]:
arr = np.array([1,2,3,4,5,6,7,8])

In [5]:
arr[-1:-5:-1]

array([8, 7, 6, 5])

In [6]:
arr[: : 2]

array([1, 3, 5, 7])

In [9]:
arr[1 : ]

array([2, 3, 4, 5, 6, 7, 8])

In [10]:
a = np.array([10,20,30,40,50])

In [11]:
a[:: 2]

array([10, 30, 50])

In [12]:
arr[-1]

np.int64(8)

In [13]:
print(arr[-1])

8


In [14]:
matrix = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

In [15]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [17]:
print(matrix[1: , 1:])

[[5 6]
 [8 9]]


In [18]:
arr = np.array([10,20,30,40,50])
ind = [0,2]
print(np.take(arr,ind))

[10 30]


In [20]:
for x in np.nditer(arr):
  print(x , end= " ")

10 20 30 40 50 

In [26]:
array = np.array([[1,2,3] , [3,4,6]])


In [27]:
for ind , x in np.ndenumerate(array):
  print(ind, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 3
(1, 1) 4
(1, 2) 6


View Vs Copy

In [28]:
arr = np.array([1,2,3,4,5,6])

In [31]:
view = arr[1:5]

In [32]:
view

array([2, 3, 4, 5])

In [33]:
view[0] = 20

In [34]:
view

array([20,  3,  4,  5])

In [35]:
array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [36]:
copy = array[1:5].copy()

In [37]:
copy

array([2, 3, 4, 5])

In [38]:
copy[0] = 20

In [39]:
copy

array([20,  3,  4,  5])

In [40]:
array

array([1, 2, 3, 4, 5, 6])